/*
 * InstantMessenger.java
 *
 * Created on 11. Juni 2005, 10:21
 */

package lgwclient.plugins;

import lgwclient.Preference;

import org.jdom.*;
import org.jdom.output.*;

/**
 *
 * @author  jfried
 */
public class InstantMessenger extends lgwclient.LgwPlugin
{
    public Preference getPreference()
    {
        return new Preference();
    }
    
    public void recieveEvent(org.jdom.Document d)
    {
        System.out.println("IM: Hab WAS!!!!");
    }
    
    public javax.swing.JPanel getWorkspace()
    {
        return this;
    }
    
    /** Creates new form InstantMessenger */
    public InstantMessenger() 
    {
        super();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        splitMainPane = new javax.swing.JSplitPane();
        scrollPeopleView = new javax.swing.JScrollPane();
        lstOnlineUser = new javax.swing.JList();
        panelMessageView = new javax.swing.JPanel();
        txtMessageText = new javax.swing.JTextArea();
        txtInputText = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        splitMainPane.setDividerSize(2);
        splitMainPane.setOneTouchExpandable(true);
        scrollPeopleView.setViewportView(lstOnlineUser);

        splitMainPane.setLeftComponent(scrollPeopleView);

        panelMessageView.setLayout(new java.awt.BorderLayout());

        panelMessageView.add(txtMessageText, java.awt.BorderLayout.CENTER);

        panelMessageView.add(txtInputText, java.awt.BorderLayout.SOUTH);

        splitMainPane.setRightComponent(panelMessageView);

        add(splitMainPane, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList lstOnlineUser;
    private javax.swing.JPanel panelMessageView;
    private javax.swing.JScrollPane scrollPeopleView;
    private javax.swing.JSplitPane splitMainPane;
    private javax.swing.JTextField txtInputText;
    private javax.swing.JTextArea txtMessageText;
    // End of variables declaration//GEN-END:variables
    
}
