/*
 * ClientGUI.java
 *
 * Created on 5. Juni 2005, 16:36
 */

package lgwclient;

import java.awt.Dimension;
import java.io.*;
import java.util.*;

import org.jdom.*;

/**
 *
 * @author  jfried
 */
public class ClientGUI extends javax.swing.JFrame 
{
    
    private String StatusBarStandardText = "Linoratix Groupware 0.1 -//- Client";
    protected Preference prefs;
    protected Thread t;
    
    /** Creates new form ClientGUI */
    public ClientGUI(Preference p) {
        initComponents();
        lblStatusBar.setText(StatusBarStandardText);
        prefs = p;
        setBounds(0, 0, 640, 480);
        panelPaneAction.setBackground(new java.awt.Color(102, 102, 102));
        scrollPaneActions.setMinimumSize(new Dimension(150, 0));
        
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        splitPaneMain = new javax.swing.JSplitPane();
        scrollPaneActions = new javax.swing.JScrollPane();
        panelPaneAction = new javax.swing.JPanel();
        scrollPaneMainFrame = new javax.swing.JScrollPane();
        tblBarMain = new javax.swing.JToolBar();
        btnTblBarMain_Exit = new javax.swing.JButton();
        panelStatusBar = new javax.swing.JPanel();
        lblStatusBar = new javax.swing.JLabel();
        lblStatusBarConnectionState = new javax.swing.JLabel();
        mnuMainMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFileExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuEditPreferences = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmMain");
        scrollPaneActions.setAutoscrolls(true);
        panelPaneAction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneActions.setViewportView(panelPaneAction);

        splitPaneMain.setLeftComponent(scrollPaneActions);

        scrollPaneMainFrame.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        splitPaneMain.setRightComponent(scrollPaneMainFrame);

        getContentPane().add(splitPaneMain, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(btnTblBarMain_Exit, "Beenden");
        btnTblBarMain_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTblBarMain_ExitActionPerformed(evt);
            }
        });

        tblBarMain.add(btnTblBarMain_Exit);

        getContentPane().add(tblBarMain, java.awt.BorderLayout.NORTH);

        panelStatusBar.setLayout(new java.awt.BorderLayout());

        panelStatusBar.setBorder(new javax.swing.border.CompoundBorder());
        org.openide.awt.Mnemonics.setLocalizedText(lblStatusBar, "Linoratix Groupware 0.1 -//- Client");
        panelStatusBar.add(lblStatusBar, java.awt.BorderLayout.WEST);

        org.openide.awt.Mnemonics.setLocalizedText(lblStatusBarConnectionState, "...");
        panelStatusBar.add(lblStatusBarConnectionState, java.awt.BorderLayout.EAST);

        getContentPane().add(panelStatusBar, java.awt.BorderLayout.SOUTH);

        org.openide.awt.Mnemonics.setLocalizedText(mnuFile, "&Datei");
        mnuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileActionPerformed(evt);
            }
        });

        mnuFileExit.setLabel("Beenden");
        mnuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileExitActionPerformed(evt);
            }
        });
        mnuFileExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuFileExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuFileExitMouseExited(evt);
            }
        });

        mnuFile.add(mnuFileExit);

        mnuMainMenu.add(mnuFile);

        org.openide.awt.Mnemonics.setLocalizedText(mnuEdit, "&Bearbeiten");
        mnuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(mnuEditPreferences, "Item");
        mnuEditPreferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuEditPreferencesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuEditPreferencesMouseExited(evt);
            }
        });

        mnuEdit.add(mnuEditPreferences);

        mnuMainMenu.add(mnuEdit);

        setJMenuBar(mnuMainMenu);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void mnuEditPreferencesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuEditPreferencesMouseExited
        lblStatusBar.setText(StatusBarStandardText);
    }//GEN-LAST:event_mnuEditPreferencesMouseExited

    private void mnuEditPreferencesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuEditPreferencesMouseEntered
        lblStatusBar.setText("Einstellungen...");
    }//GEN-LAST:event_mnuEditPreferencesMouseEntered

    private void mnuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_mnuEditActionPerformed

    private void mnuFileExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuFileExitMouseExited
        lblStatusBar.setText(StatusBarStandardText);
    }//GEN-LAST:event_mnuFileExitMouseExited

    private void mnuFileExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuFileExitMouseEntered
        lblStatusBar.setText("Linoratix Groupware Client beenden.");
    }//GEN-LAST:event_mnuFileExitMouseEntered

    private void btnTblBarMain_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTblBarMain_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnTblBarMain_ExitActionPerformed

    private void mnuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_mnuFileActionPerformed

    private void mnuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuFileExitActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTblBarMain_Exit;
    private javax.swing.JLabel lblStatusBar;
    public javax.swing.JLabel lblStatusBarConnectionState;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuEditPreferences;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFileExit;
    private javax.swing.JMenuBar mnuMainMenu;
    public javax.swing.JPanel panelPaneAction;
    private javax.swing.JPanel panelStatusBar;
    private javax.swing.JScrollPane scrollPaneActions;
    public javax.swing.JScrollPane scrollPaneMainFrame;
    private javax.swing.JSplitPane splitPaneMain;
    private javax.swing.JToolBar tblBarMain;
    // End of variables declaration//GEN-END:variables
    
}
